const MessageType = {
  MESSAGE_SENDER: 10,
  MESSAGE_RECEIVER: 11,
  MESSAGE_READ: 12,
  MESSAGE_READ_CONFIRMATION: 13,
  MESSAGE_MARK_AS_READ: 14,
  TYPE_20: 20,
  TASK_CREATE: 21, // Create a new task
  TASK_MOVE: 22,
  TASK_EDIT: 23,
  TASK_EDIT_AND_MOVE: 24,
  TASK_DESACTIVATE: 25,
  TASK_DELETE: 26,
  TASK_RESTORE: 27,
  TASK_RESTORE_ALL: 28,
  TASK_DELETE_ALL: 29,
  LOGOUT: 30,

  STATISTIC_USER: 31,
  STATISTIC_TASK: 32,
  STATISTIC_TASK_PER_STATUS: 33,
  STATISTIC_REGISTRATION: 34,
  STATISTIC_TASK_COMULATIVE: 35,
  STATISTIC_CATEGORY_COUNT: 36,
  STATISTIC_ACTIVE_USERS: 37,

  TYPE_40: 40,
};

export default MessageType;
